Bislerium.WebApp/Controllers/BlogCategoryController.cs
using Bislerium.Domain.Entity.Blogs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http.Headers;
using System.Text;

namespace Bislerium.WebApp.Controllers
{
    public class BlogCategoryController : Controller
    {
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            List<Category>? categories = new List<Category>();

            using (var httpClient  = new HttpClient())
            {
                var accessToken = Request.Cookies["access_token"];

                if (string.IsNullOrEmpty(accessToken))
                {
                    return RedirectToAction("Login");
                }

                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
                using (var response = await httpClient.GetAsync($"https://localhost:7281/api/BlogCategory/GetBlogCategories"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    categories = JsonConvert.DeserializeObject<List<Category>>(apiResponse);
                }
            }
            return View(categories);
        }

        public IActionResult Create()
        {
            return PartialView();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Category category)
        {
            using (var httpClient = new HttpClient())
            {
                var accessToken = Request.Cookies["access_token"];

                if (string.IsNullOrEmpty(accessToken))
                {
                    return RedirectToAction("Login");
                }

                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
                StringContent content = new StringContent(JsonConvert.SerializeObject(category), Encoding.UTF8, "application/json");

                using (var response = await httpClient.PostAsync("https://localhost:7281/api/BlogCategory/AddBlogCategory", content))
                {
                    string apiresponse = await response.Content.ReadAsStringAsync();
                }
            }
            return RedirectToAction("Index");
        }

        
        public async Task<IActionResult> Update(Guid id)
        {
            Category category = new Category();

            using (var httpClient = new HttpClient())
            {
                var accessToken = Request.Cookies["access_token"];

                if (string.IsNullOrEmpty(accessToken))
                {
                    return RedirectToAction("Login");
                }

                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
                using (var response = await httpClient.GetAsync($"https://localhost:7281/api/BlogCategory/GetBlogCategory/{id}"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    category = JsonConvert.DeserializeObject<Category>(apiResponse);
                }
            }
            return PartialView(category);
        }

        [HttpPost]
        public async Task<IActionResult> Update(Category category)
        {
            using (var httpClient = new HttpClient())
            {
                var accessToken = Request.Cookies["access_token"];

                if (string.IsNullOrEmpty(accessToken))
                {
                    return RedirectToAction("Login");
                }

                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
                StringContent content = new StringContent(JsonConvert.SerializeObject(category), Encoding.UTF8, "application/json");

                using (var response = await httpClient.PutAsync($"https://localhost:7281/api/BlogCategory/UpdateBlogCategory", content))
                {
                    string apiresponse = await response.Content.ReadAsStringAsync();
                }
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(Guid id)
        {
            using (var httpClient = new HttpClient())
            {
                var accessToken = Request.Cookies["access_token"];

                if (string.IsNullOrEmpty(accessToken))
                {
                    return RedirectToAction("Login");
                }

                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
                using (var response = await httpClient.DeleteAsync($"https://localhost:7281/api/BlogCategory/DeleteBlogCategory/{id}"))
                {
                    string apiresponse = await response.Content.ReadAsStringAsync();
                }
            }
            return RedirectToAction("Index");
        }
    }
}

Bislerium.WebApp/Views/BlogCategory/Create.cshtml
@model Bislerium.Domain.Entity.Blogs.Category

@{
    ViewData["Title"] = "Create";
}


<form asp-action="Create">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="staticBackdropLabel">
                Add Category
            </h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NameOfCategory" class="control-label"></label>
                <input asp-for="NameOfCategory" class="form-control" />
                <span asp-validation-for="NameOfCategory" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
            <input type="submit" value="Add" class="btn btn-primary" />
        </div>
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Bislerium.WebApp/Views/BlogCategory/Index.cshtml
@model IEnumerable<Bislerium.Domain.Entity.Blogs.Category>

@{
    Layout = "_Admin";
    ViewData["Title"] = "Index";
    int count = 1;
}


<div class="container">
    <p>
        <a asp-action="Create" class="btn btn-outline-primary" data-ajax="true" data-ajax-method="get"
           data-ajax-update="#page" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
            <i class="bi bi-plus-circle-fill"></i>
            New Category
        </a>
    </p>
    <div class="card">
        <div class="card-header">
            <h5>Categories</h5>
        </div>
        <div class="card-body">
            <table class="table table-responsive">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>
                            @Html.DisplayNameFor(model => model.NameOfCategory)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Description)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@count</td>
                            <td>
                                @Html.DisplayFor(modelItem => item.NameOfCategory)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Description)
                            </td>
                            <td>

                                <a class="btn btn-primary" asp-action="Update" asp-route-id="@item.Id" asp-controller="BlogCategory" data-ajax="true" data-ajax-method="get"
                                   data-ajax-update="#page" data-bs-toggle="modal" data-bs-target="#staticBackdrop">Update</a>
                                <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id" asp-controller="BlogCategory">Delete</a>

                            </td>
                        </tr>
                        count++;
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog" id="page">
    </div>
</div>

Bislerium.WebApp/Views/BlogCategory/Update.cshtml
@model Bislerium.Domain.Entity.Blogs.Category

@{
    ViewData["Title"] = "Update";
}



<form asp-action="Create">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="staticBackdropLabel">
                Update Category
            </h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NameOfCategory" class="control-label"></label>
                <input asp-for="NameOfCategory" class="form-control" />
                <span asp-validation-for="NameOfCategory" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="Id" class="form-control" hidden />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="CreatedAt" class="form-control" hidden />
                <span asp-validation-for="CreatedAt" class="text-danger"></span>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
            <input type="submit" value="Update" class="btn btn-primary" />
        </div>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}