Bislerium.WebApp/Controllers/BlogController.cs
using Bislerium.Domain.Entity.Blogs;
using Bislerium.Domain.Entity.History;
using Bislerium.Domain.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System.Net.Http.Headers;
using System.Reflection.Metadata;
using System.Text;

namespace Bislerium.WebApp.Controllers
{
    public class BlogController : Controller
    {
        private readonly IWebHostEnvironment _env;

        public BlogController(IWebHostEnvironment env)
        {
            _env = env;
        }

        private async Task<List<Blog>> GetAllBlogs(int? pageno, int? no)
        {
            var blogs = new List<Blog>();

            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync($"https://localhost:7281/api/Blog/GetBlogs/{pageno}/{no}"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    blogs = JsonConvert.DeserializeObject<List<Blog>>(apiResponse);
                }
            }
            return blogs;
        }

        public async Task<IActionResult> Index(int? pageno, int? no)
        {
            TempData["Pageno"] = pageno != null ? pageno : 1;
            TempData["SortBy"] = (no != null) ? no : 3;
            if (pageno == null)
            {
                pageno = 1;
            }
            if (no == null)
            {
                no = 2;
            }

            var result = await GetAllBlogs(pageno+1, no);
            
            ViewBag.HasNext = (result.Count == 0) ? false: true;

            return View(await GetAllBlogs(pageno, no));
        }

        private async Task<List<Blog>> ListBlogs()
        {
            var blogs = new List<Blog>();

            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync($"https://localhost:7281/api/Blog/GetBlogs"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    blogs = JsonConvert.DeserializeObject<List<Blog>>(apiResponse);
                }
            }
            return blogs;
        }

        public async Task<IActionResult> ListUserBlog(string id)
        {
            var blogs = await ListBlogs();
            blogs = blogs.Where(x => x.Blogger == id).ToList() != null ? blogs.Where(x => x.Blogger == id).ToList() : null;

            return View(blogs);
        }


        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> ListAllBlogs()
        {
            return View(await ListBlogs());
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Details(Guid id)
        {
            var blogdetails = new List<BlogHistory>();

            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync($"https://localhost:7281/api/Blog/GetBlogDetail/{id}"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    blogdetails = JsonConvert.DeserializeObject<List<BlogHistory>>(apiResponse);
                }
            }
            return View(blogdetails);
        }

        private static async Task<List<Category>> AllCategories()
        {
            List<Category> blogCategories = new List<Category>();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("https://localhost:7281/api/BlogCategory/GetBlogCategories"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    blogCategories = JsonConvert.DeserializeObject<List<Category>>(apiResponse);
                }
            }
            return blogCategories;
        }

        [Authorize(Roles = "Admin, Blogger")]
        public async Task<IActionResult> Create()
        {
            List<Category> blogCategories = await AllCategories();
            var elist = new SelectList(blogCategories, nameof(Category.Id), nameof(Category.NameOfCategory));
            ViewBag.eventList = elist;
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin, Blogger")]
        public async Task<IActionResult> Create(Blog blog, IFormFile? fileUpload)
        {
            int ThreeMegaBytes = 3 * 1024 * 1024;
            if (fileUpload != null && fileUpload.Length > 0)
            {
                long fileSize = fileUpload.Length;
                if(fileSize > ThreeMegaBytes)
                {
                    TempData["error"] = "Image is more than 3 mb";
                    List<Category> blogCategories = await AllCategories();
                    var elist = new SelectList(blogCategories, nameof(Category.Id), nameof(Category.NameOfCategory));
                    ViewBag.eventList = elist;
                    return View(blog);
                }

                string filename = Guid.NewGuid() + Path.GetExtension(fileUpload.FileName);
                string imgpath = Path.Combine(_env.WebRootPath, "images/blogs/", filename);
                using (FileStream streamread = new FileStream(imgpath, FileMode.Create))
                {
                    fileUpload.CopyTo(streamread);
                }
                blog.ImageUrl = filename;
            }

            using (var httpClient = new HttpClient())
            {
                var accessToken = Request.Cookies["access_token"];

                if (string.IsNullOrEmpty(accessToken))
                {
                    return RedirectToAction("Login");
                }

                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);


                StringContent content = new StringContent(JsonConvert.SerializeObject(blog), Encoding.UTF8, "application/json");

                using (var response = await httpClient.PostAsync("https://localhost:7281/api/Blog/AddBlog", content))
                {
                    string apiresponse = await response.Content.ReadAsStringAsync();
                    if (response.IsSuccessStatusCode)
                    {
                        TempData["success"] = "Blog added successfully";
                    }
                    else
                    {
                        TempData["error"] = "Please. Try again.";
                    }
                }
            }
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin, Blogger")]
        public async Task<IActionResult> Update(Guid id)
        {
            Blog blog = new();
            List<Category> blogCategories = new List<Category>();

            using (var httpClient = new HttpClient())
            {
                var accessToken = Request.Cookies["access_token"];

                if (string.IsNullOrEmpty(accessToken))
                {
                    return RedirectToAction("Login");
                }

                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);

                using (var response = await httpClient.GetAsync($"https://localhost:7281/api/Blog/GetBlog/{id}"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    blog = JsonConvert.DeserializeObject<Blog>(apiResponse);
                }

                using (var response = await httpClient.GetAsync("https://localhost:7281/api/BlogCategory/GetBlogCategories"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    blogCategories = JsonConvert.DeserializeObject<List<Category>>(apiResponse);
                }

                var elist = new SelectList(blogCategories, nameof(Category.Id), nameof(Category.NameOfCategory));
                ViewBag.eventList = elist;
            }
            return PartialView(blog);
        }

        [HttpPost]
        [Authorize(Roles = "Admin, Blogger")]
        public async Task<IActionResult> Update(Blog blog, IFormFile? fileUpload)
        {
            int ThreeMegaBytes = 3 * 1024 * 1024;
            if (fileUpload != null && fileUpload.Length > 0)
            {
                long fileSize = fileUpload.Length;
                if (fileSize > ThreeMegaBytes)
                {
                    TempData["error"] = "Image is more than 3 mb";
                    return View(blog);
                }
                string filename = Guid.NewGuid() + Path.GetExtension(fileUpload.FileName);
                string imgpath = Path.Combine(_env.WebRootPath, "images/blogs/", filename);
                using (FileStream streamread = new FileStream(imgpath, FileMode.Create))
                {
                    fileUpload.CopyTo(streamread);
                }
                blog.ImageUrl = filename;
            }
            using (var httpClient = new HttpClient())
            {
                var accessToken = Request.Cookies["access_token"];

                if (string.IsNullOrEmpty(accessToken))
                {
                    return RedirectToAction("Login");
                }

                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);

                StringContent content = new StringContent(JsonConvert.SerializeObject(blog), Encoding.UTF8, "application/json");

                using (var response = await httpClient.PutAsync($"https://localhost:7281/api/Blog/UpdateBlog", content))
                {
                    string apiresponse = await response.Content.ReadAsStringAsync();
                    if (response.IsSuccessStatusCode)
                    {

Bislerium.WebApp/Controllers/UpVoteBlogController.cs
using Bislerium.Domain.Entity.Blogs;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http.Headers;
using System.Text;

namespace Bislerium.WebApp.Controllers
{
    public class UpVoteBlogController : Controller
    {
        [HttpPost]
        public async Task<IActionResult> Create(LikeBlog vote)
        {
            using (var httpClient = new HttpClient())
            {
                var accessToken = Request.Cookies["access_token"];

                if (string.IsNullOrEmpty(accessToken))
                {
                    return RedirectToAction("Login");
                }

                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);

                StringContent content = new StringContent(JsonConvert.SerializeObject(vote), Encoding.UTF8, "application/json");

                using (var response = await httpClient.PostAsync("https://localhost:7281/api/UpVoteBlog/Reaction", content))
                {
                    string apiresponse = await response.Content.ReadAsStringAsync();
                    if (apiresponse == "true")
                    {
                        TempData["success"] = (vote.Reaction == Domain.Enums.ReactionType.UpVote) ? "Upvote Successfully added" : "Downvote Successfully added";
                    }
                    else
                    {
                        TempData["error"] = "Removed successful.";
                    }
                }
            }
            return RedirectToAction("Index", "Blog");
        }
    }
}

Bislerium.WebApp/Views/Blog/Create.cshtml
@using System.Security.Claims
@model Bislerium.Domain.Entity.Blogs.Blog

@{
    ViewData["Title"] = "Create";
}


<div class="container">
    <div class="row justify-content-center align-items-center m-3">
        <div class="col-md-6">
            <div class="card shadow-lg p-4" style="border-radius: 0px 30px">
                <h3 class="card-title mb-4">Post a New Blog</h3>
                <form asp-action="Create" asp-controller="Blog" method="post" enctype="multipart/form-data">
                    <input asp-for="Blogger" value="@User.FindFirstValue(ClaimTypes.NameIdentifier)?.ToString()" hidden />
                    <div class="mb-3">
                        <label for="title" class="form-label">Title</label>
                        <input type="text" asp-for="Title" class="form-control" placeholder="Enter your blog title" required />
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label for="content" class="form-label">Content</label>
                        <textarea id="content" asp-for="Content" class="form-control" rows="5" placeholder="Enter your blog content"></textarea>
                        <span asp-validation-for="Content" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label for="blogType" class="form-label">Select Blog Type</label>
                        <select asp-items="@ViewBag.EventList" asp-for="Category" class="form-control"></select>
                        <span asp-validation-for="Category" class="text-danger"></span>
                    </div>

                    <div class="mb-3">
                        <label for="ImageUrl" class="form-label">Blog Image</label>
                        <input type="file" id="fileUpload" class="form-control" onchange="compressAndValidate(this)" name="fileUpload">
                        <span class="text-danger"></span>
                        <div class="image-preview-container mt-2" style="display: none;">
                            <img src="#" alt="Image Preview" id="imagePreview" class="image-preview" height="100px" width="100px">
                        </div>
                    </div>
                    <div class="text-center">
                        <button type="submit" class="btn btn-primary w-100">Post</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script src="~/js/filemanager.js"></script>
<script>
    document.addEventListener("DOMContentLoaded", function () {
        const input = document.getElementById('fileUpload');
        const imagePreviewContainer = document.querySelector('.image-preview-container');
        const imagePreview = document.getElementById('imagePreview');

        input.addEventListener('change', function () {
            const file = this.files[0];
            if (file) {
                const reader = new FileReader();
                reader.onload = function (e) {
                    imagePreview.src = e.target.result;
                    imagePreviewContainer.style.display = 'block';
                };
                reader.readAsDataURL(file);
            } else {
                imagePreview.src = '#';
                imagePreviewContainer.style.display = 'none';
            }
        });
    });
</script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Bislerium.WebApp/Views/Blog/Details.cshtml
@model IEnumerable<Bislerium.Domain.Entity.History.BlogHistory>

@{
    Layout = "_Admin";
    ViewData["Title"] = "Detail";
}

<div class="card">
    <div class="card-header d-flex justify-content-between align-items-center">
        <h5 class="mb-0">Blog Detail of @Model?.FirstOrDefault()?.Blog?.Title</h5>

    </div>
    <div class="card-body">

        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Title)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Content)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.ImageUrl)
                    </th>

                    <th>
                        UpdateAt
                    </th>

                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Title)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Content)
                        </td>
                        <td>
                            @if (!string.IsNullOrEmpty(item.ImageUrl))
                            {
                                <img src="~/images/blogs/@item.ImageUrl" height="50px" width="50px" />
                            }
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.CreatedAt)
                        </td>

                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Bislerium.WebApp/Views/Blog/Index.cshtml
@using Bislerium.Domain.Enums
@using System.Security.Claims
@using Bislerium.Domain.ViewModels
@using Bislerium.Domain.Entity.Blogs
@model IEnumerable<Bislerium.Domain.Entity.Blogs.Blog>

@{
    ViewData["Title"] = "Index";
    var userId = User.Identity.IsAuthenticated ? User.FindFirstValue(ClaimTypes.NameIdentifier).ToString() : null;
}

<div class="row justify-content-end">
    <div class="col-md-auto">
        <form id="sortForm" method="get">
            <input type="hidden" name="pageno" id="currentPage" value="@TempData["Pageno"]">
            <input type="hidden" id="currentSortBy" value="@TempData["SortBy"]">

            <select name="no" class="form-select mr-2" onchange="submitForm()">
                <option value="" selected disabled>Sort option</option>
                <option value="0" selected="@((int)TempData["SortBy"] == 0)">Date</option>
                <option value="1" selected="@((int)TempData["SortBy"] == 1)">Popularity</option>
                <option value="2" selected="@((int)TempData["SortBy"] == 2)">Random</option>
            </select>
        </form>
    </div>
</div>

@foreach (var item in Model)
{
    var wordCount = item.Content.Split(new char[] { ' ', '\n' }, StringSplitOptions.RemoveEmptyEntries).Length;
    var minutesToRead = (int)Math.Ceiling((double)wordCount / 200);


    <div class="blog-card row mb-4">
        <div class="col-md-8 offset-md-2">
            <div class="card shadow rounded-5">
                <div class="card-body">
                    <div class="row">

                        <div class="col author-info">
                            <div class="d-flex align-items-start">
                                <img class="rounded-circle me-3 avatar" src="~/images/Profiles/@item.User.ProfileUrl" alt="avatar" width="60" height="60" />
                                <div>
                                    @if (User.Identity.IsAuthenticated)
                                    {

                                        @if (item.User.Id == userId)
                                        {
                                            <a asp-action="Index" asp-controller="Profile" asp-route-id="@item.User.Id" class="text-decoration-none">
                                                <h6 class="fw-bold text-black mb-1">@item.User.Name</h6>
                                            </a>
                                        }
                                        else
                                        {
                                            <a asp-action="UserProfile" asp-controller="Profile" asp-route-id="@item.User.Id" class="text-decoration-none">
                                                <h6 class="fw-bold text-black mb-1">@item.User.Name</h6>
                                            </a>
                                        }

                                    }
                                    else
                                    {
                                        <h6 class="fw-bold text-black mb-1">@item.User.Name</h6>
                                    }
                                    <p class="text-muted small mb-0">@item.CreatedAt.ToString("dd-MMM-yyyy")</p>
                                    <p class="text-muted read-time">Read Time: @minutesToRead minutes</p>

                                </div>
                            </div>
                            <div class="card-text mt-3 content-preview">
                                <p class="fw-bolder">
                                    <a asp-action="Index" asp-controller="Comment" asp-route-id="@item.Id" asp-route-userId="@userId" class="text-decoration-none">
                                        @item.Title
                                    </a>

                                </p>

                                @Html.Raw(item.Content.Length > 300 ? item.Content.Substring(0, 300) + "..." : item.Content)
                                @if (item.Content.Length > 300)
                                {
                                    <a asp-action="Index" asp-controller="Comment" asp-route-id="@item.Id" asp-route-userId="@userId" class="text-decoration-none">Continue</a>
                                }

                            </div>
                        </div>
                        @if (!string.IsNullOrEmpty(item.ImageUrl))
                        {
                            <div class="col-md-6">
                                <img src="~/Images/Blogs/@item.ImageUrl" class="card-img-top img-fluid blog-image" alt="Blog Image" />
                            </div>
                        }
                    </div>
                </div>
                <div class="card-footer bg-transparent d-flex justify-content-between align-items-center interaction-buttons">
                    @if (User.Identity.IsAuthenticated)
                    {

                        <form class="likeForm" asp-action="Create" asp-controller="UpVoteBlog">
                            <input name="LikedBlog" value="@item.Id" hidden />
                            <input name="Reaction" value="@ReactionType.UpVote" hidden />
                            <input name="LikedUser" value="@userId" hidden />
                            <button class="btn btn-outline-primary btn-sm" type="submit">
                                @Html.DisplayFor(modelItem => item.UpVotes)
                                UpVote
                            </button>
                        </form>

                        <form class="likeForm" asp-action="Create" asp-controller="UpVoteBlog">
                            <input name="LikedBlog" value="@item.Id" hidden />
                            <input name="Reaction" value="@ReactionType.DownVote" hidden />
                            <input name="LikedUser" value="@userId" hidden />
                            <button class="btn btn-outline-danger btn-sm" type="submit">
                                @Html.DisplayFor(modelItem => item.DownVotes)
                                DownVote
                            </button>
                        </form>
                    }
                    else
                    {
                        <button class="btn btn-outline-primary btn-sm" type="submit" disabled>
                            @Html.DisplayFor(modelItem => item.UpVotes)
                            UpVote
                        </button>


                        <button class="btn btn-outline-danger btn-sm" type="submit" disabled>
                            @Html.DisplayFor(modelItem => item.DownVotes)
                            DownVote
                        </button>
                    }
                    <a asp-action="Index" asp-controller="Comment" asp-route-id="@item.Id" asp-route-userId="@userId" class="btn btn-sm btn-outline-dark">Comment</a>
                </div>
            </div>
        </div>
    </div>
}
<div class="text-center">
    <form id="sortForm" method="get">
        <input type="hidden" name="pageno" id="currentPage" value="@TempData["Pageno"]">
        <input type="hidden" id="currentSortBy" value="@TempData["SortBy"]">
        @if ((int)TempData["Pageno"] != 1)
        {
            <button class="btn btn-primary" type="button" onclick="navigatePage(-1)">Previous</button>
        }
        else
        {
            <button class="btn btn-primary" type="button" onclick="navigatePage(-1)" disabled>Previous</button>
        }
        @if (ViewBag.HasNext)
        {
            <button class="btn btn-primary" type="button" onclick="navigatePage(1)">Next</button>
        }
        else
        {
            <button class="btn btn-primary" type="button" onclick="navigatePage(1)" disabled>Next</button>
        }
    </form>
</div>


<script>
    function submitForm() {
        document.getElementById("sortForm").submit();
    }

    function navigatePage(offset) {
        var currentPage = parseInt(document.getElementById("currentPage").value) || 1; 
        var newPage = currentPage + offset;
        if (newPage >= 1) {
            document.getElementById("currentPage").value = newPage;
            document.getElementById("sortForm").submit(); 
        }
    }
</script>

Bislerium.WebApp/Views/Blog/ListUserBlog.cshtml
@using Bislerium.Domain.Enums
@using System.Security.Claims
@model IEnumerable<Bislerium.Domain.Entity.Blogs.Blog>


@{
    Layout = "_Profile";
    string userId = User.FindFirstValue(ClaimTypes.NameIdentifier).ToString();
}

@foreach (var item in Model)
{
    var wordCount = item.Content.Split(new char[] { ' ', '\n' }, StringSplitOptions.RemoveEmptyEntries).Length;
    var minutesToRead = (int)Math.Ceiling((double)wordCount / 200);


    <div class="blog-card row mb-4">
        <div class="col-md-8 offset-md-2">
            <div class="card shadow rounded-5">
                <div class="card-body">
                    <div class="row">

                        <div class="col author-info">
                            <div class="d-flex align-items-start">
                                <img class="rounded-circle me-3 avatar" src="~/images/Profiles/@item.User.ProfileUrl" alt="avatar" width="60" height="60" />
                                <div>

                                    <h6 class="fw-bold text-black mb-1">@item.User.Name</h6>

                                    <p class="text-muted small mb-0">@item.CreatedAt.ToString("MMM yyyy")</p>
                                    <p class="text-muted read-time">Read Time: @minutesToRead minutes</p>
                                    <div class="dropdown">
                                        <button class="btn btn-sm btn-secondary mb-2 mb-md-0 dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                                            Options
                                        </button>
                                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                            <li>
                                                <a asp-route-Id="@item.Id" asp-action="Update" asp-controller="Blog" class="dropdown-item" data-ajax="true" data-ajax-method="get" data-ajax-update="#page" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                                                    <i class="fas fa-edit"></i> Edit Blog
                                                </a>
                                            </li>
                                            <li>
                                                <a class="dropdown-item" asp-route-Id="@item.Id" asp-action="Delete" asp-controller="Blog" data-ajax="true" data-ajax-method="post" data-ajax-confirm="Are you sure?" data-ajax-complete="deletePage">
                                                    <i class="fas fa-trash-alt"></i> Delete Blog
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="card-text mt-3 content-preview">
                                <p class="fw-bolder">
                                    <a asp-action="Index" asp-controller="Comment" asp-route-id="@item.Id" asp-route-userId="@userId" class="text-decoration-none">
                                        @item.Title
                                    </a>

                                </p>

                                @Html.Raw(item.Content.Length > 300 ? item.Content.Substring(0, 300) + "..." : item.Content)
                                @if (item.Content.Length > 300)
                                {
                                    <a asp-action="Index" asp-controller="Comment" asp-route-id="@item.Id" asp-route-userId="@userId" class="text-decoration-none">Continue</a>
                                }

                            </div>
                        </div>
                        @if (!string.IsNullOrEmpty(item.ImageUrl))
                        {
                            <div class="col-md-6">
                                <img src="~/Images/Blogs/@item.ImageUrl" class="card-img-top img-fluid blog-image" alt="Blog Image" />
                            </div>
                        }
                    </div>
                </div>
                <div class="card-footer bg-transparent d-flex justify-content-between align-items-center interaction-buttons">

                    <form class="likeForm" asp-action="CreateProfile" asp-controller="UpVoteBlog">
                        <input name="LikedBlog" value="@item.Id" hidden />
                        <input name="Reaction" value="@ReactionType.UpVote" hidden />
                        <input name="LikedUser" value="@userId" hidden />
                        <button class="btn btn-outline-primary btn-sm" type="submit" disabled>
                            @Html.DisplayFor(modelItem => item.UpVotes)
                            UpVote
                        </button>
                    </form>

                    <form class="likeForm" asp-action="CreateProfile" asp-controller="UpVoteBlog">
                        <input name="LikedBlog" value="@item.Id" hidden />
                        <input name="Reaction" value="@ReactionType.DownVote" hidden />
                        <input name="LikedUser" value="@userId" hidden />
                        <button class="btn btn-outline-danger btn-sm" type="submit" disabled>
                            @Html.DisplayFor(modelItem => item.DownVotes)
                            DownVote
                        </button>
                    </form>

                    <a asp-action="Index" asp-controller="Comment" asp-route-id="@item.Id" asp-route-userId="@userId" class="btn btn-sm btn-outline-dark">Comment</a>

                </div>
            </div>
        </div>
    </div>
}

<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog" id="page">
    </div>
</div>


<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script>
    $(document).ready(function () {
        deletePage = function (xhr) {
            location.reload();
        }
    });
</script>