Bislerium.WebApp/Controllers/AdminUserController.cs
using Bislerium.Domain.Entity.Blogs;
using Bislerium.Domain.Entity.Users;
using Bislerium.Domain.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http.Headers;
using System.Text;
using Week21.Domain;

namespace Bislerium.WebApp.Controllers
{
    public class AdminUserController : Controller
    {
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index(string? role = null)
        {
            List<UserVM> allUsers = new List<UserVM>();

            using (var httpClient = new HttpClient())
            {
                var accessToken = Request.Cookies["access_token"];

                if (string.IsNullOrEmpty(accessToken))
                {
                    return RedirectToAction("Login");
                }

                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
                using (var response = await httpClient.GetAsync($"https://localhost:7281/api/Account/GetUsers"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    allUsers = JsonConvert.DeserializeObject<List<UserVM>>(apiResponse);
                }
            }

            if (!string.IsNullOrEmpty(role))
            {
                allUsers = allUsers.Where(x => x.Role == role).ToList();
            }

            return View(allUsers);
        }

        public IActionResult Create()
        {
            return PartialView();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Register register)
        {
            if (!ModelState.IsValid)
            {
                return View(register);
            }
            using (var httpClient = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(register), Encoding.UTF8, "application/json");

                using (var response = await httpClient.PostAsync("https://localhost:7281/api/Account/registerUser", content))
                {
                    string apiresponse = await response.Content.ReadAsStringAsync();
                    if (response.IsSuccessStatusCode)
                    {
                        TempData["success"] = "New Admin added successfully";
                    }
                    else
                    {
                        TempData["error"] = "There is an error try again.";
                    }
                }
            }
            return RedirectToAction("Index");
        }
    }
}

Bislerium.WebApp/Controllers/BlogController.cs
using Bislerium.Domain.Entity.Blogs;
using Bislerium.Domain.Entity.History;
using Bislerium.Domain.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System.Net.Http.Headers;
using System.Reflection.Metadata;
using System.Text;

namespace Bislerium.WebApp.Controllers
{
    public class BlogController : Controller
    {
        private readonly IWebHostEnvironment _env;

        public BlogController(IWebHostEnvironment env)
        {
            _env = env;
        }

        private async Task<List<Blog>> GetAllBlogs(int? pageno, int? no)
        {
            var blogs = new List<Blog>();

            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync($"https://localhost:7281/api/Blog/GetBlogs/{pageno}/{no}"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    blogs = JsonConvert.DeserializeObject<List<Blog>>(apiResponse);
                }
            }
            return blogs;
        }

        public async Task<IActionResult> Index(int? pageno, int? no)
        {
            TempData["Pageno"] = pageno != null ? pageno : 1;
            TempData["SortBy"] = (no != null) ? no : 3;
            if (pageno == null)
            {
                pageno = 1;
            }
            if (no == null)
            {
                no = 2;
            }

            var result = await GetAllBlogs(pageno+1, no);
            
            ViewBag.HasNext = (result.Count == 0) ? false: true;

            return View(await GetAllBlogs(pageno, no));
        }

        private async Task<List<Blog>> ListBlogs()
        {
            var blogs = new List<Blog>();

            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync($"https://localhost:7281/api/Blog/GetBlogs"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    blogs = JsonConvert.DeserializeObject<List<Blog>>(apiResponse);
                }
            }
            return blogs;
        }

        public async Task<IActionResult> ListUserBlog(string id)
        {
            var blogs = await ListBlogs();
            blogs = blogs.Where(x => x.Blogger == id).ToList() != null ? blogs.Where(x => x.Blogger == id).ToList() : null;

            return View(blogs);
        }


        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> ListAllBlogs()
        {
            return View(await ListBlogs());
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Details(Guid id)
        {
            var blogdetails = new List<BlogHistory>();

            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync($"https://localhost:7281/api/Blog/GetBlogDetail/{id}"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    blogdetails = JsonConvert.DeserializeObject<List<BlogHistory>>(apiResponse);
                }
            }
            return View(blogdetails);
        }

        private static async Task<List<Category>> AllCategories()
        {
            List<Category> blogCategories = new List<Category>();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("https://localhost:7281/api/BlogCategory/GetBlogCategories"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    blogCategories = JsonConvert.DeserializeObject<List<Category>>(apiResponse);
                }
            }
            return blogCategories;
        }

        [Authorize(Roles = "Admin, Blogger")]
        public async Task<IActionResult> Create()
        {
            List<Category> blogCategories = await AllCategories();
            var elist = new SelectList(blogCategories, nameof(Category.Id), nameof(Category.NameOfCategory));
            ViewBag.eventList = elist;
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin, Blogger")]
        public async Task<IActionResult> Create(Blog blog, IFormFile? fileUpload)
        {
            int ThreeMegaBytes = 3 * 1024 * 1024;
            if (fileUpload != null && fileUpload.Length > 0)
            {
                long fileSize = fileUpload.Length;
                if(fileSize > ThreeMegaBytes)
                {
                    TempData["error"] = "Image is more than 3 mb";
                    List<Category> blogCategories = await AllCategories();
                    var elist = new SelectList(blogCategories, nameof(Category.Id), nameof(Category.NameOfCategory));
                    ViewBag.eventList = elist;
                    return View(blog);
                }

                string filename = Guid.NewGuid() + Path.GetExtension(fileUpload.FileName);
                string imgpath = Path.Combine(_env.WebRootPath, "images/blogs/", filename);
                using (FileStream streamread = new FileStream(imgpath, FileMode.Create))
                {
                    fileUpload.CopyTo(streamread);
                }
                blog.ImageUrl = filename;
            }

            using (var httpClient = new HttpClient())
            {
                var accessToken = Request.Cookies["access_token"];

                if (string.IsNullOrEmpty(accessToken))
                {
                    return RedirectToAction("Login");
                }

                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);


                StringContent content = new StringContent(JsonConvert.SerializeObject(blog), Encoding.UTF8, "application/json");

                using (var response = await httpClient.PostAsync("https://localhost:7281/api/Blog/AddBlog", content))
                {
                    string apiresponse = await response.Content.ReadAsStringAsync();
                    if (response.IsSuccessStatusCode)
                    {
                        TempData["success"] = "Blog added successfully";
                    }
                    else
                    {
                        TempData["error"] = "Please. Try again.";
                    }
                }
            }
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin, Blogger")]
        public async Task<IActionResult> Update(Guid id)
        {
            Blog blog = new();
            List<Category> blogCategories = new List<Category>();

            using (var httpClient = new HttpClient())
            {
                var accessToken = Request.Cookies["access_token"];

                if (string.IsNullOrEmpty(accessToken))
                {
                    return RedirectToAction("Login");
                }

                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);

                using (var response = await httpClient.GetAsync($"https://localhost:7281/api/Blog/GetBlog/{id}"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    blog = JsonConvert.DeserializeObject<Blog>(apiResponse);
                }

                using (var response = await httpClient.GetAsync("https://localhost:7281/api/BlogCategory/GetBlogCategories"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    blogCategories = JsonConvert.DeserializeObject<List<Category>>(apiResponse);
                }

                var elist = new SelectList(blogCategories, nameof(Category.Id), nameof(Category.NameOfCategory));
                ViewBag.eventList = elist;
            }
            return PartialView(blog);
        }

        [HttpPost]
        [Authorize(Roles = "Admin, Blogger")]
        public async Task<IActionResult> Update(Blog blog, IFormFile? fileUpload)
        {
            int ThreeMegaBytes = 3 * 1024 * 1024;
            if (fileUpload != null && fileUpload.Length > 0)
            {
                long fileSize = fileUpload.Length;
                if (fileSize > ThreeMegaBytes)
                {
                    TempData["error"] = "Image is more than 3 mb";
                    return View(blog);
                }
                string filename = Guid.NewGuid() + Path.GetExtension(fileUpload.FileName);
                string imgpath = Path.Combine(_env.WebRootPath, "images/blogs/", filename);
                using (FileStream streamread = new FileStream(imgpath, FileMode.Create))
                {
                    fileUpload.CopyTo(streamread);
                }
                blog.ImageUrl = filename;
            }
            using (var httpClient = new HttpClient())
            {
                var accessToken = Request.Cookies["access_token"];

                if (string.IsNullOrEmpty(accessToken))
                {
                    return RedirectToAction("Login");
                }

                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);

                StringContent content = new StringContent(JsonConvert.SerializeObject(blog), Encoding.UTF8, "application/json");

                using (var response = await httpClient.PutAsync($"https://localhost:7281/api/Blog/UpdateBlog", content))
                {
                    string apiresponse = await response.Content.ReadAsStringAsync();
                    if (response.IsSuccessStatusCode)
                    {

Bislerium.WebApp/Controllers/DashboardController.cs
using Bislerium.Domain.Entity.Blogs;
using Bislerium.Domain.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http.Headers;

namespace Bislerium.WebApp.Controllers
{
    [Authorize(Roles = "Admin")]
    public class DashboardController : Controller
    {
        public async Task<IActionResult> Index(int? year, int? month)
        {
            if(year == null)
            {
                year = DateTime.Now.Year;
                month = DateTime.Now.Month;
            }
            

            DashboardVM dashboard = new DashboardVM();
            List<LikeCountVM> dailyCount = new();

            using (var httpClient = new HttpClient())
            {
                var accessToken = Request.Cookies["access_token"];

                if (string.IsNullOrEmpty(accessToken))
                {
                    return RedirectToAction("Login");
                }

                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);

                using (var response = await httpClient.GetAsync($"https://localhost:7281/api/Dashboard/GetDashboardData/{year}/{month}"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    dashboard = JsonConvert.DeserializeObject<DashboardVM>(apiResponse);
                }

                using (var response = await httpClient.GetAsync($"https://localhost:7281/api/Dashboard/LikeDislike/{year}/{month}"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    dailyCount = JsonConvert.DeserializeObject<List<LikeCountVM>>(apiResponse);
                }
            }

            ViewBag.DailyCount = dailyCount;
            ViewBag.Year = $"{year}-{month}-";
            return View(dashboard);
        }

        public async Task<IActionResult> TopTen(int? year, int? month)
        {
            if (year == null)
            {
                year = DateTime.Now.Year;
                month = DateTime.Now.Month;
            }

            TopTen top = new TopTen();

            using (var httpClient = new HttpClient())
            {
                var accessToken = Request.Cookies["access_token"];

                if (string.IsNullOrEmpty(accessToken))
                {
                    return RedirectToAction("Login");
                }

                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);

                using (var response = await httpClient.GetAsync($"https://localhost:7281/api/Dashboard/GetTopTen/{year}/{month}"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    top = JsonConvert.DeserializeObject<TopTen>(apiResponse);
                }
            }

            return View(top);
        }
    }
}

Bislerium.WebApp/Controllers/NotificationController.cs
using Microsoft.AspNetCore.Mvc;

namespace Bislerium.WebApp.Controllers
{
    public class NotificationController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Bislerium.WebApp/Views/Shared/_Admin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bislerium</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/admin.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/apexcharts.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.0/font/bootstrap-icons.css" rel="stylesheet">

    <style>
        body{
            height: 80vh;
        }

        .nav-item {
            margin-top: 25px;
        }

        .scrollable-container {
            height: 100vh;
            overflow-y: auto;
        }

        .scrollable-container::-webkit-scrollbar {
            width: 0;
        }

        .scrollable-container {
            scrollbar-width: none;
        }
    </style>
</head>
<body>
    <partial name="_Notification" />

    <div class="container-fluid">
        <div class="row flex-nowrap">
            <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 adminPanel shadow" style="background-color: #172a45">
                <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                    <a asp-action="Index" asp-controller="Blog" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                        <span class="fs-5 d-none d-sm-inline">Go to Application</span>
                    </a>
                    <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                        <li class="nav-item">
                            <a asp-action="Index" asp-controller="Dashboard" class="text-decoration-none text-white align-middle px-0">
                                <i class="bi-house fs-4 me-2"></i><span class="ms-1 d-none d-sm-inline">Home</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-action="TopTen" asp-controller="Dashboard" class="text-decoration-none text-white align-middle px-0">
                                <i class="bi-star fs-4 me-2"></i><span class="ms-1 d-none d-sm-inline">Top Ten</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-action="Index" asp-controller="AdminUser" class="text-decoration-none text-white align-middle px-0">
                                <i class="bi-people fs-4 me-2"></i><span class="ms-1 d-none d-sm-inline">Users</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-action="Index" asp-controller="BlogCategory" class="text-decoration-none text-white align-middle px-0">
                                <i class="bi-journal-plus fs-4 me-2"></i><span class="ms-1 d-none d-sm-inline">Blog Category</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-action="ListAllBlogs" asp-controller="Blog" class="text-decoration-none text-white align-middle px-0">
                                <i class="bi-journal-text fs-4 me-2"></i><span class="ms-1 d-none d-sm-inline">Blogs</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-action="ListAllComments" asp-controller="Comment" class="text-decoration-none text-white align-middle px-0">
                                <i class="bi-chat-left-text fs-4 me-2"></i><span class="ms-1 d-none d-sm-inline">Comments</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <form class="form-inline" asp-area="" asp-controller="Account" asp-action="Logout">
                                <button type="submit" class="btn text-danger btn-outline-light" data-toggle="tooltip" title="Logout">
                                    Logout
                                </button>
                            </form>
                        </li>

                    </ul>

                </div>
            </div>
            <div class="col py-3">
                <div class="container-fluid scrollable-container">
                    @RenderBody()
                </div>
            </div>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/apexcharts.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-ajax-unobtrusive/3.2.6/jquery.unobtrusive-ajax.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Bislerium.WebApp/Views/Shared/_Layout.cshtml
@using System.Security.Claims
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bislerium.WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Bislerium.WebApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.0/font/bootstrap-icons.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.min.js"></script>


</head>
<body>
    <partial name="_Notification" />
    <header>

        <nav id="navbar" class="navbar navbar-expand-sm navbar-light bg-transparent border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Blog" asp-action="Index">
                    <span style="color: #ff6b6b;">Bislerium</span>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-sm-0">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Blog" asp-action="Index">Blog</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <input type="hidden" id="userId" value="@User.FindFirstValue(ClaimTypes.NameIdentifier)">

                            var nameIdentifier = User.FindFirstValue(ClaimTypes.NameIdentifier);

                            if (nameIdentifier != null)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-action="Create" asp-controller="Blog">New Blog</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-action="Index" asp-controller="Profile" asp-route-Id="@User.FindFirstValue(ClaimTypes.NameIdentifier).ToString()">Profile</a>
                                </li>
                                <li>
                                    <span class="badge notification-count" id="notificationCount" data-toggle="popover" title="Notifications"></span>
                                </li>
                                @if (User.IsInRole("Admin"))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Dashboard" asp-action="Index">Dashboard</a>
                                    </li>
                                }
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                                </li>
                            }
                            else
                            {
                                <p>You are authenticated, but the NameIdentifier claim is missing.</p>
                            }
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted text-center">
        <div class="container">
            &copy; 2024 - Bislerium
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-ajax-unobtrusive/3.2.6/jquery.unobtrusive-ajax.min.js"></script>
    <script>
        // Initialize WOW.js
        new WOW().init();
    </script>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://www.gstatic.com/firebasejs/6.4.2/firebase-app.js" type="text/javascript"></script>
    <script src="https://www.gstatic.com/firebasejs/6.4.2/firebase-messaging.js" type="text/javascript"></script>

    <script type="module">
        $(function () {
            var token = null;

            const firebaseConfig = {
                apiKey: "AIzaSyBmH762_RXI9i8fgn4yoRR8cyPZa3kjxWQ",
                authDomain: "fire425837619.firebaseapp.com",
                projectId: "fire425837619",
                storageBucket: "fire425837619.appspot.com",
                messagingSenderId: "850063422052",
                appId: "1:850063422052:web:8584219cfc4aaaf35ca571",
                measurementId: "G-EWSKRNHETK"
            };

            firebase.initializeApp(firebaseConfig);
            const messaging = firebase.messaging();
            console.log(messaging);
            messaging.requestPermission().then(() => {
                console.log('Notification permission granted.');

                getToken();
            }).catch((err) => {
                console.error('Unable to get permission to notify.', err);
            });

            function getToken() {
                messaging.getToken().then((currentToken) => {
                    if (currentToken) {
                        console.log('FCM Token:', currentToken);
                        sendTokenToServer(currentToken);
                    } else {
                        console.log('No registration token available. Request permission to generate one.');
                    }
                }).catch((err) => {
                    console.error('An error occurred while retrieving token.', err);
                });
            }


            function isTokenSentToServer() {
                // Implement your logic to check if token is already sent to server
                return false;
            }

            function sendTokenToServer(token) {
                const userId = $("#userId").val(); // Get the user ID from the hidden input field

                const payload = {
                    userId: userId,
                    token: token
                };

                // Make AJAX request to server
                $.ajax({
                    url: "/Account/SaveToken",
                    type: "POST",
                    contentType: "application/json",
                    data: JSON.stringify(payload),
                    success: function (response) {
                        // Handle success response from server
                        console.log("Token saved successfully:", response);
                    },
                    error: function (xhr, status, error) {
                        // Handle error response from server
                        console.error("Error saving token to server:", error);
                    }
                });
            }

        });

    </script>


    @*     <script src="~/lib/microsoft/signalr/dist/browser/signalr.min.js"></script>
    <script src="~/js/notification.js"></script> *@

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>


@*
import { initializeApp } from "firebase/app";
import { getMessaging, getToken } from "firebase/messaging";
import { saveNotificationToken } from "../constants/Api";

//--------GET TOKEN FROM LOCAL STORAGE---------
const jwt = localStorage.getItem("token");

// -------------Initialize Firebase----------------
const firebaseConfig = {
  apiKey: "AIzaSyDC1ecgHuzmN2RxDyQcsHZRDSnSAaqVU0w",
  authDomain: "horizon-residence.firebaseapp.com",
  projectId: "horizon-residence",
  storageBucket: "horizon-residence.appspot.com",
  messagingSenderId: "740497421368",
  appId: "1:740497421368:web:4abea47c8416290d64a2cd",
  measurementId: "G-31KNRS5J5F",
};

const firebaseApp = initializeApp(firebaseConfig);
const messaging = getMessaging(firebaseApp);

const setupNotifications = async (message) => {
  try {
    const permission = await Notification.requestPermission();
    if (permission === "granted" && jwt) {
      console.log("Notification permission granted.");

      // Get the FCM token
      console.log(message, "Message");
      const token = await getToken(messaging);
      const data = { notification_token: token, device_type: "WEB" };
      saveNotificationToken(data, jwt)
        .then((res) => console.log(res.message))
        .catch((err) => console.log(err.response));
      console.log("FCM Token:", token);
    } else {
      console.log("Notification permission denied.");
    }
  } catch (error) {
    console.log(error);
  }
}; *@

Bislerium.WebApp/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}


@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}